# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/hdd/pr/c++/crypt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/hdd/pr/c++/crypt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/hdd/pr/c++/crypt/CMakeFiles /media/hdd/pr/c++/crypt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/hdd/pr/c++/crypt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named fragment_ncrypt

# Build rule for target.
fragment_ncrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fragment_ncrypt
.PHONY : fragment_ncrypt

# fast build rule for target.
fragment_ncrypt/fast:
	$(MAKE) -f CMakeFiles/fragment_ncrypt.dir/build.make CMakeFiles/fragment_ncrypt.dir/build
.PHONY : fragment_ncrypt/fast

#=============================================================================
# Target rules for targets named grid_ncrypt

# Build rule for target.
grid_ncrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grid_ncrypt
.PHONY : grid_ncrypt

# fast build rule for target.
grid_ncrypt/fast:
	$(MAKE) -f CMakeFiles/grid_ncrypt.dir/build.make CMakeFiles/grid_ncrypt.dir/build
.PHONY : grid_ncrypt/fast

#=============================================================================
# Target rules for targets named public_ncrypt

# Build rule for target.
public_ncrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 public_ncrypt
.PHONY : public_ncrypt

# fast build rule for target.
public_ncrypt/fast:
	$(MAKE) -f CMakeFiles/public_ncrypt.dir/build.make CMakeFiles/public_ncrypt.dir/build
.PHONY : public_ncrypt/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

lib/src/chat_message.o: lib/src/chat_message.cc.o
.PHONY : lib/src/chat_message.o

# target to build an object file
lib/src/chat_message.cc.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/lib/src/chat_message.cc.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/src/chat_message.cc.o
.PHONY : lib/src/chat_message.cc.o

lib/src/chat_message.i: lib/src/chat_message.cc.i
.PHONY : lib/src/chat_message.i

# target to preprocess a source file
lib/src/chat_message.cc.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/lib/src/chat_message.cc.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/src/chat_message.cc.i
.PHONY : lib/src/chat_message.cc.i

lib/src/chat_message.s: lib/src/chat_message.cc.s
.PHONY : lib/src/chat_message.s

# target to generate assembly for a file
lib/src/chat_message.cc.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/lib/src/chat_message.cc.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/src/chat_message.cc.s
.PHONY : lib/src/chat_message.cc.s

lib/src/fragment_ncrypt.o: lib/src/fragment_ncrypt.cc.o
.PHONY : lib/src/fragment_ncrypt.o

# target to build an object file
lib/src/fragment_ncrypt.cc.o:
	$(MAKE) -f CMakeFiles/fragment_ncrypt.dir/build.make CMakeFiles/fragment_ncrypt.dir/lib/src/fragment_ncrypt.cc.o
.PHONY : lib/src/fragment_ncrypt.cc.o

lib/src/fragment_ncrypt.i: lib/src/fragment_ncrypt.cc.i
.PHONY : lib/src/fragment_ncrypt.i

# target to preprocess a source file
lib/src/fragment_ncrypt.cc.i:
	$(MAKE) -f CMakeFiles/fragment_ncrypt.dir/build.make CMakeFiles/fragment_ncrypt.dir/lib/src/fragment_ncrypt.cc.i
.PHONY : lib/src/fragment_ncrypt.cc.i

lib/src/fragment_ncrypt.s: lib/src/fragment_ncrypt.cc.s
.PHONY : lib/src/fragment_ncrypt.s

# target to generate assembly for a file
lib/src/fragment_ncrypt.cc.s:
	$(MAKE) -f CMakeFiles/fragment_ncrypt.dir/build.make CMakeFiles/fragment_ncrypt.dir/lib/src/fragment_ncrypt.cc.s
.PHONY : lib/src/fragment_ncrypt.cc.s

lib/src/grid_ncrypt.o: lib/src/grid_ncrypt.cc.o
.PHONY : lib/src/grid_ncrypt.o

# target to build an object file
lib/src/grid_ncrypt.cc.o:
	$(MAKE) -f CMakeFiles/grid_ncrypt.dir/build.make CMakeFiles/grid_ncrypt.dir/lib/src/grid_ncrypt.cc.o
.PHONY : lib/src/grid_ncrypt.cc.o

lib/src/grid_ncrypt.i: lib/src/grid_ncrypt.cc.i
.PHONY : lib/src/grid_ncrypt.i

# target to preprocess a source file
lib/src/grid_ncrypt.cc.i:
	$(MAKE) -f CMakeFiles/grid_ncrypt.dir/build.make CMakeFiles/grid_ncrypt.dir/lib/src/grid_ncrypt.cc.i
.PHONY : lib/src/grid_ncrypt.cc.i

lib/src/grid_ncrypt.s: lib/src/grid_ncrypt.cc.s
.PHONY : lib/src/grid_ncrypt.s

# target to generate assembly for a file
lib/src/grid_ncrypt.cc.s:
	$(MAKE) -f CMakeFiles/grid_ncrypt.dir/build.make CMakeFiles/grid_ncrypt.dir/lib/src/grid_ncrypt.cc.s
.PHONY : lib/src/grid_ncrypt.cc.s

lib/src/public_ncrypt.o: lib/src/public_ncrypt.cc.o
.PHONY : lib/src/public_ncrypt.o

# target to build an object file
lib/src/public_ncrypt.cc.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/lib/src/public_ncrypt.cc.o
	$(MAKE) -f CMakeFiles/public_ncrypt.dir/build.make CMakeFiles/public_ncrypt.dir/lib/src/public_ncrypt.cc.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/src/public_ncrypt.cc.o
.PHONY : lib/src/public_ncrypt.cc.o

lib/src/public_ncrypt.i: lib/src/public_ncrypt.cc.i
.PHONY : lib/src/public_ncrypt.i

# target to preprocess a source file
lib/src/public_ncrypt.cc.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/lib/src/public_ncrypt.cc.i
	$(MAKE) -f CMakeFiles/public_ncrypt.dir/build.make CMakeFiles/public_ncrypt.dir/lib/src/public_ncrypt.cc.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/src/public_ncrypt.cc.i
.PHONY : lib/src/public_ncrypt.cc.i

lib/src/public_ncrypt.s: lib/src/public_ncrypt.cc.s
.PHONY : lib/src/public_ncrypt.s

# target to generate assembly for a file
lib/src/public_ncrypt.cc.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/lib/src/public_ncrypt.cc.s
	$(MAKE) -f CMakeFiles/public_ncrypt.dir/build.make CMakeFiles/public_ncrypt.dir/lib/src/public_ncrypt.cc.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/src/public_ncrypt.cc.s
.PHONY : lib/src/public_ncrypt.cc.s

src/client.o: src/client.cxx.o
.PHONY : src/client.o

# target to build an object file
src/client.cxx.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client.cxx.o
.PHONY : src/client.cxx.o

src/client.i: src/client.cxx.i
.PHONY : src/client.i

# target to preprocess a source file
src/client.cxx.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client.cxx.i
.PHONY : src/client.cxx.i

src/client.s: src/client.cxx.s
.PHONY : src/client.s

# target to generate assembly for a file
src/client.cxx.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client.cxx.s
.PHONY : src/client.cxx.s

src/fragment_ncrypt.o: src/fragment_ncrypt.cxx.o
.PHONY : src/fragment_ncrypt.o

# target to build an object file
src/fragment_ncrypt.cxx.o:
	$(MAKE) -f CMakeFiles/fragment_ncrypt.dir/build.make CMakeFiles/fragment_ncrypt.dir/src/fragment_ncrypt.cxx.o
.PHONY : src/fragment_ncrypt.cxx.o

src/fragment_ncrypt.i: src/fragment_ncrypt.cxx.i
.PHONY : src/fragment_ncrypt.i

# target to preprocess a source file
src/fragment_ncrypt.cxx.i:
	$(MAKE) -f CMakeFiles/fragment_ncrypt.dir/build.make CMakeFiles/fragment_ncrypt.dir/src/fragment_ncrypt.cxx.i
.PHONY : src/fragment_ncrypt.cxx.i

src/fragment_ncrypt.s: src/fragment_ncrypt.cxx.s
.PHONY : src/fragment_ncrypt.s

# target to generate assembly for a file
src/fragment_ncrypt.cxx.s:
	$(MAKE) -f CMakeFiles/fragment_ncrypt.dir/build.make CMakeFiles/fragment_ncrypt.dir/src/fragment_ncrypt.cxx.s
.PHONY : src/fragment_ncrypt.cxx.s

src/grid_ncrypt.o: src/grid_ncrypt.cxx.o
.PHONY : src/grid_ncrypt.o

# target to build an object file
src/grid_ncrypt.cxx.o:
	$(MAKE) -f CMakeFiles/grid_ncrypt.dir/build.make CMakeFiles/grid_ncrypt.dir/src/grid_ncrypt.cxx.o
.PHONY : src/grid_ncrypt.cxx.o

src/grid_ncrypt.i: src/grid_ncrypt.cxx.i
.PHONY : src/grid_ncrypt.i

# target to preprocess a source file
src/grid_ncrypt.cxx.i:
	$(MAKE) -f CMakeFiles/grid_ncrypt.dir/build.make CMakeFiles/grid_ncrypt.dir/src/grid_ncrypt.cxx.i
.PHONY : src/grid_ncrypt.cxx.i

src/grid_ncrypt.s: src/grid_ncrypt.cxx.s
.PHONY : src/grid_ncrypt.s

# target to generate assembly for a file
src/grid_ncrypt.cxx.s:
	$(MAKE) -f CMakeFiles/grid_ncrypt.dir/build.make CMakeFiles/grid_ncrypt.dir/src/grid_ncrypt.cxx.s
.PHONY : src/grid_ncrypt.cxx.s

src/public_ncrypt.o: src/public_ncrypt.cxx.o
.PHONY : src/public_ncrypt.o

# target to build an object file
src/public_ncrypt.cxx.o:
	$(MAKE) -f CMakeFiles/public_ncrypt.dir/build.make CMakeFiles/public_ncrypt.dir/src/public_ncrypt.cxx.o
.PHONY : src/public_ncrypt.cxx.o

src/public_ncrypt.i: src/public_ncrypt.cxx.i
.PHONY : src/public_ncrypt.i

# target to preprocess a source file
src/public_ncrypt.cxx.i:
	$(MAKE) -f CMakeFiles/public_ncrypt.dir/build.make CMakeFiles/public_ncrypt.dir/src/public_ncrypt.cxx.i
.PHONY : src/public_ncrypt.cxx.i

src/public_ncrypt.s: src/public_ncrypt.cxx.s
.PHONY : src/public_ncrypt.s

# target to generate assembly for a file
src/public_ncrypt.cxx.s:
	$(MAKE) -f CMakeFiles/public_ncrypt.dir/build.make CMakeFiles/public_ncrypt.dir/src/public_ncrypt.cxx.s
.PHONY : src/public_ncrypt.cxx.s

src/server.o: src/server.cxx.o
.PHONY : src/server.o

# target to build an object file
src/server.cxx.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cxx.o
.PHONY : src/server.cxx.o

src/server.i: src/server.cxx.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cxx.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cxx.i
.PHONY : src/server.cxx.i

src/server.s: src/server.cxx.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cxx.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cxx.s
.PHONY : src/server.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... client"
	@echo "... edit_cache"
	@echo "... fragment_ncrypt"
	@echo "... grid_ncrypt"
	@echo "... public_ncrypt"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... lib/src/chat_message.o"
	@echo "... lib/src/chat_message.i"
	@echo "... lib/src/chat_message.s"
	@echo "... lib/src/fragment_ncrypt.o"
	@echo "... lib/src/fragment_ncrypt.i"
	@echo "... lib/src/fragment_ncrypt.s"
	@echo "... lib/src/grid_ncrypt.o"
	@echo "... lib/src/grid_ncrypt.i"
	@echo "... lib/src/grid_ncrypt.s"
	@echo "... lib/src/public_ncrypt.o"
	@echo "... lib/src/public_ncrypt.i"
	@echo "... lib/src/public_ncrypt.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/fragment_ncrypt.o"
	@echo "... src/fragment_ncrypt.i"
	@echo "... src/fragment_ncrypt.s"
	@echo "... src/grid_ncrypt.o"
	@echo "... src/grid_ncrypt.i"
	@echo "... src/grid_ncrypt.s"
	@echo "... src/public_ncrypt.o"
	@echo "... src/public_ncrypt.i"
	@echo "... src/public_ncrypt.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

